# -*- coding: utf-8 -*-
"""Transac ai model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MaXTmi1q971GD_V0Wz2_b2yKvv6CowS3
"""

# ── CELL 1: Upload & Load Dataset ─────────────────────────────────────────
from google.colab import files

uploaded = files.upload()  # Select Super_Dataset_Combined.xlsx when prompted
print("✅ File uploaded successfully")

print(df['User'].unique())

import pandas as pd

# Just read the file directly (already uploaded in Colab)
df = pd.read_excel("Super_Dataset_Combined.xlsx")

# Convert Date column
df['Date'] = pd.to_datetime(df['Date'])

# 🔁 CHANGE THIS anytime
user_name = "Divine Ehinomeh Martins"

# Filter user
user_df = df[df['User'] == user_name].copy()

if user_df.empty:
    print(f"No data found for {user_name}")
else:
    # Sort by date
    user_df = user_df.sort_values(by='Date')

    # Start & End date
    start_date = user_df['Date'].min()
    end_date = user_df['Date'].max()

    # Monthly spending
    user_df['YearMonth'] = user_df['Date'].dt.to_period('M')
    monthly = user_df.groupby('YearMonth')['Debit'].sum()

    highest_month = monthly.idxmax()
    lowest_month = monthly.idxmin()

    # Balances
    highest_balance = user_df['Balance'].max()
    lowest_balance = user_df['Balance'].min()
    current_balance = user_df.iloc[-1]['Balance']

    # Totals
    total_credit = user_df['Credit'].sum()
    total_debit = user_df['Debit'].sum()

    # Categories
    categories = user_df['Category'].dropna().unique()

    # Print results
    print("========== USER FINANCIAL SUMMARY ==========")
    print(f"User Name: {user_name}")
    print(f"Start Date: {start_date}")
    print(f"End Date: {end_date}")
    print(f"Highest Spending Month: {highest_month}")
    print(f"Lowest Spending Month: {lowest_month}")
    print(f"Highest Balance Ever: ₦{highest_balance:,.2f}")
    print(f"Lowest Balance Ever: ₦{lowest_balance:,.2f}")
    print(f"Current Balance: ₦{current_balance:,.2f}")
    print(f"Total Credit: ₦{total_credit:,.2f}")
    print(f"Total Debit (Spending): ₦{total_debit:,.2f}")
    print(f"Categories: {list(categories)}")
    # Highest spending category
category_spending = user_df.groupby('Category')['Debit'].sum()

highest_category = category_spending.idxmax()
highest_category_amount = category_spending.max()
print(f"Highest Spending Category: {highest_category} (₦{highest_category_amount:,.2f})")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Style
plt.rcParams['figure.dpi'] = 150
plt.rcParams['font.family'] = 'DejaVu Sans'
sns.set_theme(style='whitegrid', palette='muted')

# Load
df = pd.read_excel('Super_Dataset_Combined.xlsx')
df['Date']       = pd.to_datetime(df['Date'])
df['Month']      = df['Date'].dt.month
df['MonthName']  = df['Date'].dt.strftime('%b %Y')
df['DayOfWeek']  = df['Date'].dt.day_name()
df['DayOfMonth'] = df['Date'].dt.day
df['IsWeekend']  = df['Date'].dt.dayofweek.isin([5, 6]).astype(int)
df['Week']       = df['Date'].dt.isocalendar().week.astype(int)
df['YearMonth']  = df['Date'].dt.to_period('M')
df['Year']       = df['Date'].dt.year

print("✅ Dataset loaded")
print(f"   Rows      : {len(df)}")
print(f"   Columns   : {df.columns.tolist()}")
print(f"   Date range: {df['Date'].min().date()} → {df['Date'].max().date()}")
print(f"   Users     : {df['User'].unique().tolist()}")
print(f"   Banks     : {df['Bank'].unique().tolist()}")
df.head(10)

# ── CELL 2: Dataset Overview ──────────────────────────────────────────────
print("=" * 60)
print("DATASET OVERVIEW")
print("=" * 60)

print(f"\nShape: {df.shape[0]} rows × {df.shape[1]} columns\n")

print("Column Data Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nBasic Statistics (Debit, Credit & Balance):")
print(df[['Debit','Credit','Balance']].describe().round(2))

print("\nTransaction count per User:")
print(df.groupby('User').size().sort_values(ascending=False).to_frame('Transactions'))

print("\nTransaction count per Bank:")
print(df.groupby('Bank').size().sort_values(ascending=False).to_frame('Transactions'))

print("\nTransaction count per User + Bank:")
print(df.groupby(['User','Bank']).size().to_frame('Transactions'))

# ── DIVINE EHINOMEH MARTINS — Full Spending Analysis ──────────────────────
divine = df[df['User'] == 'Divine Ehinomeh Martins'].copy()

print(f"Divine's transactions : {len(divine)}")
print(f"Date range            : {divine['Date'].min().date()} → {divine['Date'].max().date()}")
print(f"Total Spent           : ₦{divine['Debit'].sum():,.2f}")
print(f"Total Received        : ₦{divine['Credit'].sum():,.2f}")
print(f"Net Position          : ₦{(divine['Credit'].sum() - divine['Debit'].sum()):,.2f}")

fig, axes = plt.subplots(3, 2, figsize=(16, 18))
fig.suptitle("Divine Ehinomeh Martins — Spending Analysis", fontsize=16, fontweight='bold', y=1.01)

# ── Plot 1: Spending by Category (horizontal bar) ─────────────────────────
cat_spend = divine.groupby('Category')['Debit'].sum().sort_values(ascending=True)
cat_spend = cat_spend[cat_spend > 0]
colors = sns.color_palette("RdYlGn_r", len(cat_spend))
cat_spend.plot(kind='barh', ax=axes[0,0], color=colors, edgecolor='white')
axes[0,0].set_title("Total Spend by Category", fontweight='bold')
axes[0,0].set_xlabel("Amount (₦)")
axes[0,0].xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
for i, v in enumerate(cat_spend):
    axes[0,0].text(v + 500, i, f'₦{v:,.0f}', va='center', fontsize=7)

# ── Plot 2: Monthly Debit vs Credit ───────────────────────────────────────
monthly = divine.groupby(divine['Date'].dt.to_period('M')).agg(
    Debit=('Debit','sum'), Credit=('Credit','sum')).reset_index()
monthly['Date'] = monthly['Date'].astype(str)
x = range(len(monthly))
width = 0.35
axes[0,1].bar([i - width/2 for i in x], monthly['Debit'],  width, label='Debit (Spent)',    color='#e74c3c', alpha=0.85)
axes[0,1].bar([i + width/2 for i in x], monthly['Credit'], width, label='Credit (Received)', color='#2ecc71', alpha=0.85)
axes[0,1].set_xticks(list(x))
axes[0,1].set_xticklabels(monthly['Date'], rotation=45, ha='right', fontsize=8)
axes[0,1].set_title("Monthly Income vs Expenses", fontweight='bold')
axes[0,1].set_ylabel("Amount (₦)")
axes[0,1].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
axes[0,1].legend()

# ── Plot 3: Category Transaction Count (pie) ──────────────────────────────
cat_count = divine['Category'].value_counts()
top_cats  = cat_count[:7]
other_sum = cat_count[7:].sum()
if other_sum > 0:
    top_cats['Other Categories'] = other_sum
axes[1,0].pie(top_cats, labels=top_cats.index, autopct='%1.1f%%',
              startangle=140, colors=sns.color_palette('Set2', len(top_cats)))
axes[1,0].set_title("Transaction Count by Category", fontweight='bold')

# ── Plot 4: Daily Spending Trend (rolling 7-day) ──────────────────────────
daily = divine.groupby('Date')['Debit'].sum().reset_index()
daily['Rolling7'] = daily['Debit'].rolling(7).mean()
axes[1,1].fill_between(daily['Date'], daily['Debit'], alpha=0.3, color='#e74c3c', label='Daily Spend')
axes[1,1].plot(daily['Date'], daily['Rolling7'], color='#c0392b', linewidth=2, label='7-Day Rolling Avg')
axes[1,1].set_title("Daily Spending Trend", fontweight='bold')
axes[1,1].set_ylabel("Amount (₦)")
axes[1,1].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
axes[1,1].legend()
axes[1,1].tick_params(axis='x', rotation=45)

# ── Plot 5: Spending by Day of Week ───────────────────────────────────────
dow_order = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
dow_spend = divine.groupby('DayOfWeek')['Debit'].sum().reindex(dow_order)
bar_colors = ['#e74c3c' if d in ['Saturday','Sunday'] else '#3498db' for d in dow_order]
dow_spend.plot(kind='bar', ax=axes[2,0], color=bar_colors, edgecolor='white')
axes[2,0].set_title("Spending by Day of Week\n(Red = Weekend)", fontweight='bold')
axes[2,0].set_ylabel("Amount (₦)")
axes[2,0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
axes[2,0].tick_params(axis='x', rotation=45)

# ── Plot 6: Top 10 Largest Single Transactions ────────────────────────────
top10 = divine.nlargest(10, 'Debit')[['Date','Category','Description','Debit']].copy()
top10['Description'] = top10['Description'].str[:30]
axes[2,1].barh(range(len(top10)), top10['Debit'], color='#e67e22', edgecolor='white')
axes[2,1].set_yticks(range(len(top10)))
axes[2,1].set_yticklabels([f"{r['Description'][:25]}..." for _, r in top10.iterrows()], fontsize=8)
axes[2,1].set_title("Top 10 Largest Transactions", fontweight='bold')
axes[2,1].set_xlabel("Amount (₦)")
axes[2,1].xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))

plt.tight_layout()
plt.savefig('divine_eda.png', bbox_inches='tight', dpi=150)
plt.show()
print("✅ Divine EDA complete")

# ── DIVINE: Detailed Category Breakdown ───────────────────────────────────
divine = df[df['User'] == 'Divine Ehinomeh Martins'].copy()

print("=" * 60)
print("DIVINE EHINOMEH MARTINS — DETAILED SPENDING BREAKDOWN")
print("=" * 60)

summary = divine.groupby('Category').agg(
    Transactions = ('Debit', 'count'),
    Total_Spent  = ('Debit', 'sum'),
    Avg_Per_Txn  = ('Debit', 'mean'),
    Max_Txn      = ('Debit', 'max')
).sort_values('Total_Spent', ascending=False).round(2)

summary['% of Total Spend'] = (summary['Total_Spent'] / summary['Total_Spent'].sum() * 100).round(1)
summary['Total_Spent']      = summary['Total_Spent'].apply(lambda x: f'₦{x:,.2f}')
summary['Avg_Per_Txn']      = summary['Avg_Per_Txn'].apply(lambda x: f'₦{x:,.2f}')
summary['Max_Txn']          = summary['Max_Txn'].apply(lambda x: f'₦{x:,.2f}')

print(summary.to_string())

print("\n")
print(f"💰 Total Spent       : ₦{divine['Debit'].sum():,.2f}")
print(f"💵 Total Received    : ₦{divine['Credit'].sum():,.2f}")
print(f"📊 Net Position      : ₦{(divine['Credit'].sum() - divine['Debit'].sum()):,.2f}")
print(f"📅 Avg Daily Spend   : ₦{divine.groupby('Date')['Debit'].sum().mean():,.2f}")
print(f"📅 Avg Monthly Spend : ₦{divine.groupby(divine['Date'].dt.to_period('M'))['Debit'].sum().mean():,.2f}")
print(f"🔢 Most Active Category: {divine['Category'].value_counts().index[0]} ({divine['Category'].value_counts().iloc[0]} transactions)")

divine = df[df['User'] == 'Divine Ehinomeh Martins'].copy()

print("=" * 60)
print("DIVINE — FINANCIAL HEALTH SUMMARY")
print("=" * 60)

total_in     = divine['Credit'].sum()
total_out    = divine['Debit'].sum()
net          = total_in - total_out
savings_rate = ((total_in - total_out) / total_in * 100) if total_in > 0 else 0

print(f"\n💵 Total Income (Credits)  : ₦{total_in:,.2f}")
print(f"💸 Total Expenses (Debits) : ₦{total_out:,.2f}")
print(f"💰 Net Savings             : ₦{net:,.2f}")
print(f"📊 Savings Rate            : {savings_rate:.1f}%")

if savings_rate >= 20:
    health = "🟢 HEALTHY — Saving more than 20% of income"
elif savings_rate >= 10:
    health = "🟡 MODERATE — Saving between 10–20% of income"
elif savings_rate >= 0:
    health = "🟠 AT RISK — Saving less than 10% of income"
else:
    health = "🔴 CRITICAL — Spending more than earning"
print(f"🏥 Financial Health        : {health}")

import matplotlib.ticker as mticker
divine = df[df['User'] == 'Divine Ehinomeh Martins'].copy()

monthly = divine.groupby(divine['Date'].dt.to_period('M')).agg(
    Income  = ('Credit', 'sum'),
    Expense = ('Debit',  'sum')
).reset_index()
monthly['Savings']      = monthly['Income'] - monthly['Expense']
monthly['Savings_Rate'] = (monthly['Savings'] / monthly['Income'] * 100).round(1)
monthly['Date']         = monthly['Date'].astype(str)

fig, axes = plt.subplots(2, 1, figsize=(14, 10))
fig.suptitle("Divine — Monthly Financial Flow & Savings Rate", fontsize=14, fontweight='bold')

colors = ['#2ecc71' if x >= 0 else '#e74c3c' for x in monthly['Savings']]
axes[0].bar(monthly['Date'], monthly['Savings'], color=colors, edgecolor='white')
axes[0].axhline(0, color='black', linewidth=0.8, linestyle='--')
axes[0].set_title("Monthly Net Savings (Green = Saved, Red = Overspent)", fontweight='bold')
axes[0].set_ylabel("Amount (₦)")
axes[0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
axes[0].tick_params(axis='x', rotation=45)
for i, (val, date) in enumerate(zip(monthly['Savings'], monthly['Date'])):
    axes[0].text(i, val + (500 if val >= 0 else -2000), f'₦{val:,.0f}',
                ha='center', fontsize=7, fontweight='bold')

axes[1].plot(monthly['Date'], monthly['Savings_Rate'],
             marker='o', color='#8e44ad', linewidth=2.5, markersize=8)
axes[1].axhline(20, color='green', linewidth=1, linestyle='--', label='Healthy (20%)')
axes[1].axhline(0,  color='red',   linewidth=1, linestyle='--', label='Break Even (0%)')
axes[1].fill_between(range(len(monthly)), monthly['Savings_Rate'], 0,
                     where=[x >= 0 for x in monthly['Savings_Rate']],
                     alpha=0.15, color='green')
axes[1].fill_between(range(len(monthly)), monthly['Savings_Rate'], 0,
                     where=[x < 0 for x in monthly['Savings_Rate']],
                     alpha=0.15, color='red')
axes[1].set_title("Monthly Savings Rate (%)", fontweight='bold')
axes[1].set_ylabel("Savings Rate (%)")
axes[1].set_xticks(range(len(monthly)))
axes[1].set_xticklabels(monthly['Date'], rotation=45, ha='right', fontsize=8)
axes[1].legend()

plt.tight_layout()
plt.savefig('divine_savings_trend.png', bbox_inches='tight', dpi=150)
plt.show()
print(monthly[['Date','Income','Expense','Savings','Savings_Rate']].to_string(index=False))

divine = df[df['User'] == 'Divine Ehinomeh Martins'].copy()
divine['IsWeekend'] = divine['Date'].dt.dayofweek.isin([5,6]).astype(int)
divine['DayOfWeek'] = divine['Date'].dt.day_name()
divine['YearMonth'] = divine['Date'].dt.to_period('M')

print("=" * 60)
print("DIVINE — SPENDING BEHAVIOUR PATTERNS")
print("=" * 60)

# Weekend vs Weekday
weekend_spend = divine[divine['IsWeekend'] == 1]['Debit'].sum()
weekday_spend = divine[divine['IsWeekend'] == 0]['Debit'].sum()
weekend_txns  = len(divine[divine['IsWeekend'] == 1])
weekday_txns  = len(divine[divine['IsWeekend'] == 0])

print(f"\n📅 WEEKEND vs WEEKDAY SPENDING")
print(f"   Weekend Total : ₦{weekend_spend:,.2f} across {weekend_txns} transactions")
print(f"   Weekday Total : ₦{weekday_spend:,.2f} across {weekday_txns} transactions")
print(f"   Weekend Avg   : ₦{weekend_spend/weekend_txns if weekend_txns > 0 else 0:,.2f} per transaction")
print(f"   Weekday Avg   : ₦{weekday_spend/weekday_txns if weekday_txns > 0 else 0:,.2f} per transaction")

# Monthly spending stats
monthly_exp = divine.groupby(divine['Date'].dt.to_period('M'))['Debit'].sum()
print(f"\n📆 MONTHLY SPENDING PATTERNS")
print(f"   Most Expensive Month : {monthly_exp.idxmax()} — ₦{monthly_exp.max():,.2f}")
print(f"   Cheapest Month       : {monthly_exp.idxmin()} — ₦{monthly_exp.min():,.2f}")
print(f"   Average Monthly Spend: ₦{monthly_exp.mean():,.2f}")
print(f"   Monthly Std Dev      : ₦{monthly_exp.std():,.2f}")

# Transaction size distribution
print(f"\n💳 TRANSACTION SIZE DISTRIBUTION")
bins   = [0, 500, 2000, 10000, 50000, float('inf')]
labels = ['Micro (₦0–500)', 'Small (₦501–2K)', 'Medium (₦2K–10K)', 'Large (₦10K–50K)', 'Very Large (₦50K+)']
debit_only = divine[divine['Debit'] > 0].copy()
debit_only['TxnSize'] = pd.cut(debit_only['Debit'], bins=bins, labels=labels)
txn_dist = debit_only['TxnSize'].value_counts().sort_index()
for label, count in txn_dist.items():
    pct = count / txn_dist.sum() * 100
    print(f"   {label:<25}: {count:>4} transactions ({pct:.1f}%)")

# Category consistency across months
total_months = divine['YearMonth'].nunique()
print(f"\n🔄 CATEGORY CONSISTENCY (out of {total_months} months)")
cat_months = divine.groupby('Category')['YearMonth'].nunique().sort_values(ascending=False)
for cat, months in cat_months.items():
    pct = months / total_months * 100
    bar = '█' * int(pct / 10)
    print(f"   {cat:<22}: {months}/{total_months} months ({pct:.0f}%) {bar}")

import matplotlib.ticker as mticker
divine = df[df['User'] == 'Divine Ehinomeh Martins'].copy()

print("=" * 60)
print("DIVINE — FINANCIAL LEAKAGE PREVIEW")
print("=" * 60)

leakage_cats  = ['Betting', 'Charges', 'SMS Charges', 'Card Maintenance', 'Tax']
leakage       = divine[divine['Category'].isin(leakage_cats)]
total_spend   = divine['Debit'].sum()
leakage_spend = leakage['Debit'].sum()
leakage_pct   = leakage_spend / total_spend * 100 if total_spend > 0 else 0

print(f"\n⚠️  Total Financial Leakage : ₦{leakage_spend:,.2f}")
print(f"   % of Total Spending     : {leakage_pct:.1f}%")
print(f"   Number of Transactions  : {len(leakage)}")
print()
for cat in leakage_cats:
    cat_df = divine[divine['Category'] == cat]
    amount = cat_df['Debit'].sum()
    count  = len(cat_df)
    if amount > 0:
        print(f"   {cat:<22}: ₦{amount:,.2f} across {count} transactions")

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("Divine — Financial Leakage Analysis", fontsize=13, fontweight='bold')

productive_cats = ['Savings', 'Data Purchase', 'Airtime', 'Electricity', 'School']
productive = divine[divine['Category'].isin(productive_cats)]['Debit'].sum()
p2p        = divine[divine['Category'] == 'P2P Transfer']['Debit'].sum()
pos        = divine[divine['Category'] == 'POS Transaction']['Debit'].sum()
other_sp   = total_spend - leakage_spend - productive - p2p - pos

spend_breakdown = pd.Series({
    'P2P Transfers' : p2p,
    'POS Purchases' : pos,
    'Productive'    : productive,
    'Leakage'       : leakage_spend,
    'Other'         : max(other_sp, 0)
})
spend_breakdown = spend_breakdown[spend_breakdown > 0]
colors = ['#3498db','#e67e22','#2ecc71','#e74c3c','#95a5a6']
axes[0].pie(spend_breakdown, labels=spend_breakdown.index,
            autopct='%1.1f%%', colors=colors[:len(spend_breakdown)], startangle=140)
axes[0].set_title("Spend Breakdown: Productive vs Leakage", fontweight='bold')

leakage_by_cat = leakage.groupby('Category')['Debit'].sum().sort_values(ascending=False)
if len(leakage_by_cat) > 0:
    leakage_by_cat.plot(kind='bar', ax=axes[1], color='#e74c3c', edgecolor='white')
    axes[1].set_title("Leakage Amount by Category", fontweight='bold')
    axes[1].set_ylabel("Amount (₦)")
    axes[1].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
    axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.savefig('divine_leakage.png', bbox_inches='tight', dpi=150)
plt.show()

# ── DIVINE: TRANSACTION COUNT BY CATEGORY — FILTERED BY MONTH OR WEEK ────
# Paste this cell right after the divine_leakage section

divine = df[df['User'] == 'Divine Ehinomeh Martins'].copy()
divine['YearMonth'] = divine['Date'].dt.to_period('M')
divine['YearWeek']  = divine['Date'].dt.to_period('W')

# ── CONFIG: change these two lines to explore ─────────────────────────────
FILTER_BY = 'month'    # 'month'  or  'week'
PERIOD    = '2025-10'  # for month: '2025-10' | for week: run once to see available weeks

# ── Show available periods ─────────────────────────────────────────────────
if FILTER_BY == 'month':
    available = sorted([str(p) for p in divine['YearMonth'].unique()])
    print("📅 Available months:", available)
    subset = divine[divine['YearMonth'].astype(str) == PERIOD]
    period_label = PERIOD
elif FILTER_BY == 'week':
    available = sorted([str(p) for p in divine['YearWeek'].unique()])
    print("📅 Available weeks:", available)
    subset = divine[divine['YearWeek'].astype(str) == PERIOD]
    period_label = f"Week {PERIOD}"

# ── Count & print ──────────────────────────────────────────────────────────
cat_count = subset['Category'].value_counts()
print(f"\n📊 Transaction Count by Category — {period_label}")
print(cat_count.to_string())

# ── Pie + Bar side by side ────────────────────────────────────────────────
if cat_count.empty:
    print("⚠️  No data for this period — check your PERIOD value above")
else:
    fig, axes = plt.subplots(1, 2, figsize=(16, 7))
    fig.suptitle(f"Divine — Transaction Count by Category ({period_label})",
                 fontsize=14, fontweight='bold')

    colors = sns.color_palette('Set2', len(cat_count))

    # Pie
    wedges, texts, autotexts = axes[0].pie(
        cat_count, labels=cat_count.index, autopct='%1.1f%%',
        startangle=140, colors=colors, pctdistance=0.82
    )
    for at in autotexts: at.set_fontsize(9)
    axes[0].set_title("Share (%)", fontweight='bold')

    # Bar (absolute)
    bars = axes[1].bar(cat_count.index, cat_count.values, color=colors, edgecolor='white')
    axes[1].set_title("Absolute Count", fontweight='bold')
    axes[1].set_ylabel("Number of Transactions")
    axes[1].tick_params(axis='x', rotation=45)
    for bar, val in zip(bars, cat_count.values):
        axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,
                     str(val), ha='center', va='bottom', fontweight='bold')

    plt.tight_layout()
    plt.savefig(f'divine_pie_{FILTER_BY}_{PERIOD}.png', bbox_inches='tight', dpi=150)
    plt.show()
    print(f"✅ Saved → divine_pie_{FILTER_BY}_{PERIOD}.png")

# ── ALL MONTHS: one pie per month in a grid ───────────────────────────────
months = sorted(divine['YearMonth'].unique())
cols = 4
rows = (len(months) + cols - 1) // cols

fig, axes = plt.subplots(rows, cols, figsize=(cols*5, rows*4.5))
fig.suptitle("Divine — Transaction Count by Category (All Months)",
             fontsize=15, fontweight='bold', y=1.01)
axes = axes.flatten()
palette = sns.color_palette('Set2', 10)

for i, month in enumerate(months):
    sub = divine[divine['YearMonth'] == month]
    cc  = sub['Category'].value_counts()
    ax  = axes[i]
    if cc.empty:
        ax.set_visible(False)
        continue
    ax.pie(cc, labels=cc.index, autopct='%1.0f%%',
           startangle=140, colors=palette[:len(cc)], pctdistance=0.80)
    for t in ax.texts: t.set_fontsize(7)
    ax.set_title(str(month), fontweight='bold', fontsize=10)

for j in range(i+1, len(axes)):
    axes[j].set_visible(False)

plt.tight_layout()
plt.savefig('divine_all_monthly_pies.png', bbox_inches='tight', dpi=150)
plt.show()
print("✅ All monthly pies → divine_all_monthly_pies.png")

# ── DIVINE: WHO SHE SENDS MONEY TO — FILTERABLE BY MONTH / WEEK / YEAR ───

divine = df[df['User'] == 'Divine Ehinomeh Martins'].copy()
divine['Date']      = pd.to_datetime(divine['Date'])
divine['YearMonth'] = divine['Date'].dt.to_period('M')
divine['YearWeek']  = divine['Date'].dt.to_period('W')
divine['Year']      = divine['Date'].dt.year

# Keep only outgoing P2P transfers
sent = divine[
    (divine['Category'] == 'P2P Transfer') &
    (divine['Description'].str.lower().str.startswith('transfer to', na=False))
].copy()

# Extract recipient name
sent['Recipient'] = sent['Description'].str.replace(
    r'^Transfer to\s+', '', case=False, regex=True).str.strip()

# ── CONFIG ────────────────────────────────────────────────────────────────
FILTER_BY = 'month'   # 'month'  |  'week'  |  'year'
PERIOD    = '2025-10' # month: '2025-10' | week: '2025-W41' | year: 2025
TOP_N     = 10        # how many top recipients to show

# ── Filter ────────────────────────────────────────────────────────────────
if FILTER_BY == 'month':
    available = sorted([str(p) for p in sent['YearMonth'].unique()])
    print("📅 Available months:", available)
    subset = sent[sent['YearMonth'].astype(str) == PERIOD]
    period_label = PERIOD

elif FILTER_BY == 'week':
    available = sorted([str(p) for p in sent['YearWeek'].unique()])
    print("📅 Available weeks:", available)
    subset = sent[sent['YearWeek'].astype(str) == str(PERIOD)]
    period_label = f"Week {PERIOD}"

elif FILTER_BY == 'year':
    available = sorted(sent['Year'].unique().tolist())
    print("📅 Available years:", available)
    subset = sent[sent['Year'] == int(PERIOD)]
    period_label = str(PERIOD)

# ── Aggregate ─────────────────────────────────────────────────────────────
recipient_count  = subset.groupby('Recipient')['Debit'].count().sort_values(ascending=False).head(TOP_N)
recipient_amount = subset.groupby('Recipient')['Debit'].sum().reindex(recipient_count.index)

print(f"\n📊 Top {TOP_N} Recipients — {period_label}")
for r, count, amt in zip(recipient_count.index, recipient_count.values, recipient_amount.values):
    print(f"   {r:<45}: {count:>3}x  ₦{amt:,.2f}")

# ── Chart ─────────────────────────────────────────────────────────────────
if recipient_count.empty:
    print("⚠️  No outgoing transfers for this period — check your PERIOD value")
else:
    fig, axes = plt.subplots(1, 2, figsize=(18, 6))
    fig.suptitle(f"Divine — Who She Sends Money To ({period_label})",
                 fontsize=14, fontweight='bold')

    colors = sns.color_palette('Blues_r', len(recipient_count))

    # Left: frequency (how many times)
    bars = axes[0].barh(recipient_count.index[::-1], recipient_count.values[::-1],
                        color=colors, edgecolor='white')
    axes[0].set_title(f"Number of Transfers (Top {TOP_N})", fontweight='bold')
    axes[0].set_xlabel("Transfer Count")
    for bar, val in zip(bars, recipient_count.values[::-1]):
        axes[0].text(bar.get_width() + 0.1, bar.get_y() + bar.get_height()/2,
                     f'{val}x', va='center', fontweight='bold', fontsize=9)

    # Right: total amount sent
    colors2 = sns.color_palette('Reds_r', len(recipient_amount))
    bars2 = axes[1].barh(recipient_amount.index[::-1], recipient_amount.values[::-1],
                         color=colors2, edgecolor='white')
    axes[1].set_title(f"Total Amount Sent (Top {TOP_N})", fontweight='bold')
    axes[1].set_xlabel("Amount (₦)")
    axes[1].xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
    for bar, val in zip(bars2, recipient_amount.values[::-1]):
        axes[1].text(bar.get_width() + 500, bar.get_y() + bar.get_height()/2,
                     f'₦{val:,.0f}', va='center', fontsize=8)

    plt.tight_layout()
    plt.savefig(f'divine_recipients_{FILTER_BY}_{PERIOD}.png', bbox_inches='tight', dpi=150)
    plt.show()
    print(f"\n✅ Saved → divine_recipients_{FILTER_BY}_{PERIOD}.png")

# ── DIVINE: ANOMALY DETECTION — Unusual Spending Months & Weeks ─────────────
# Paste this right after the "WHO SHE SENDS MONEY TO" section

divine = df[df['User'] == 'Divine Ehinomeh Martins'].copy()
divine['YearMonth'] = divine['Date'].dt.to_period('M')
divine['YearWeek']  = divine['Date'].dt.to_period('W')

# ── Aggregate daily → monthly & weekly spending ─────────────────────────────
monthly_spend = divine.groupby('YearMonth')['Debit'].sum().reset_index()
monthly_spend = monthly_spend.rename(columns={'Debit': 'Total_Spent'})

weekly_spend  = divine.groupby('YearWeek')['Debit'].sum().reset_index()
weekly_spend  = weekly_spend.rename(columns={'Debit': 'Total_Spent'})

# ── Z-score anomaly detection (threshold = 2.0) ─────────────────────────────
def flag_anomalies(series, threshold=2.0):
    mean = series.mean()
    std  = series.std()
    z_scores = (series - mean) / std
    anomalies = z_scores.abs() > threshold
    return anomalies, z_scores, mean, std

# Monthly anomalies
monthly_spend['Anomaly'], monthly_spend['Z_Score'], m_mean, m_std = flag_anomalies(monthly_spend['Total_Spent'])

# Weekly anomalies
weekly_spend['Anomaly'], weekly_spend['Z_Score'], w_mean, w_std = flag_anomalies(weekly_spend['Total_Spent'])

# ── PRINT SUMMARY ───────────────────────────────────────────────────────────
print("=" * 70)
print("DIVINE — ANOMALY DETECTION (Unusual Spending)")
print("=" * 70)

print(f"\n📅 MONTHLY ANOMALIES (Z > 2.0)")
print(f"   Average monthly spend : ₦{m_mean:,.0f}  |  Std : ₦{m_std:,.0f}")
anomalous_months = monthly_spend[monthly_spend['Anomaly']]
if anomalous_months.empty:
    print("   ✅ No unusual months detected")
else:
    for _, row in anomalous_months.iterrows():
        print(f"   🚨 {row['YearMonth']} → ₦{row['Total_Spent']:,.0f}  (Z = {row['Z_Score']:.2f})")

print(f"\n📅 WEEKLY ANOMALIES (Z > 2.0)")
print(f"   Average weekly spend  : ₦{w_mean:,.0f}  |  Std : ₦{w_std:,.0f}")
anomalous_weeks = weekly_spend[weekly_spend['Anomaly']]
if anomalous_weeks.empty:
    print("   ✅ No unusual weeks detected")
else:
    for _, row in anomalous_weeks.iterrows():
        print(f"   🚨 {row['YearWeek']} → ₦{row['Total_Spent']:,.0f}  (Z = {row['Z_Score']:.2f})")

# ── VISUALISATION: Monthly + Weekly with highlighted anomalies ──────────────
fig, axes = plt.subplots(2, 1, figsize=(16, 10))
fig.suptitle("Divine — Anomaly Detection: Unusual Spending Months & Weeks",
             fontsize=16, fontweight='bold', y=1.02)

# Monthly
colors_m = ['#e74c3c' if a else '#3498db' for a in monthly_spend['Anomaly']]
axes[0].bar(monthly_spend['YearMonth'].astype(str), monthly_spend['Total_Spent'],
            color=colors_m, edgecolor='white')
axes[0].axhline(m_mean, color='black', linestyle='--', label=f'Avg ₦{m_mean:,.0f}')
axes[0].set_title("Monthly Spending (Red = Anomaly)", fontweight='bold')
axes[0].set_ylabel("Amount (₦)")
axes[0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
axes[0].tick_params(axis='x', rotation=45)
axes[0].legend()

# Weekly
colors_w = ['#e74c3c' if a else '#3498db' for a in weekly_spend['Anomaly']]
axes[1].bar(weekly_spend['YearWeek'].astype(str), weekly_spend['Total_Spent'],
            color=colors_w, edgecolor='white')
axes[1].axhline(w_mean, color='black', linestyle='--', label=f'Avg ₦{w_mean:,.0f}')
axes[1].set_title("Weekly Spending (Red = Anomaly)", fontweight='bold')
axes[1].set_ylabel("Amount (₦)")
axes[1].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
axes[1].tick_params(axis='x', rotation=90)
axes[1].legend()

plt.tight_layout()
plt.savefig('divine_anomaly_detection.png', bbox_inches='tight', dpi=150)
plt.show()

print("\n✅ Saved → divine_anomaly_detection.png")
print("   (You can now change the threshold above from 2.0 to 1.5 or 3.0 if you want stricter/looser flags)")

# ── DIVINE: BALANCE TRAJECTORY ────────────────────────────────────────────

divine = df[df['User'] == 'Divine Ehinomeh Martins'].copy()
divine['Date']      = pd.to_datetime(divine['Date'])
divine['YearMonth'] = divine['Date'].dt.to_period('M')

# Sort by date to get correct trajectory
divine = divine.sort_values('Date').reset_index(drop=True)

# Daily closing balance (last balance entry per day)
daily_balance = divine.groupby('Date')['Balance'].last().reset_index()
daily_balance['Rolling30'] = daily_balance['Balance'].rolling(30).mean()

# Monthly avg balance
monthly_balance = divine.groupby('YearMonth')['Balance'].mean().reset_index()
monthly_balance['Month_str'] = monthly_balance['YearMonth'].astype(str)

print("=" * 60)
print("DIVINE — BALANCE TRAJECTORY")
print("=" * 60)
print(f"\n💰 Starting Balance : ₦{daily_balance['Balance'].iloc[0]:,.2f}")
print(f"💰 Ending Balance   : ₦{daily_balance['Balance'].iloc[-1]:,.2f}")
print(f"📈 Peak Balance     : ₦{daily_balance['Balance'].max():,.2f}  on {daily_balance.loc[daily_balance['Balance'].idxmax(), 'Date'].date()}")
print(f"📉 Lowest Balance   : ₦{daily_balance['Balance'].min():,.2f}  on {daily_balance.loc[daily_balance['Balance'].idxmin(), 'Date'].date()}")
print(f"📊 Avg Balance      : ₦{daily_balance['Balance'].mean():,.2f}")

# How many days was balance below 1000 (danger zone)
danger_days = (daily_balance['Balance'] < 1000).sum()
print(f"⚠️  Days below ₦1,000: {danger_days} days")

fig, axes = plt.subplots(3, 1, figsize=(16, 14))
fig.suptitle("Divine — Balance Trajectory Over Time", fontsize=15, fontweight='bold')

# Plot 1: Full daily balance line
axes[0].plot(daily_balance['Date'], daily_balance['Balance'],
             color='#3498db', linewidth=1.2, alpha=0.7, label='Daily Balance')
axes[0].plot(daily_balance['Date'], daily_balance['Rolling30'],
             color='#e74c3c', linewidth=2, label='30-Day Rolling Avg')
axes[0].axhline(1000, color='orange', linestyle='--', linewidth=1, label='Danger Zone (₦1K)')
axes[0].fill_between(daily_balance['Date'], daily_balance['Balance'], 0,
                     where=daily_balance['Balance'] < 1000,
                     color='red', alpha=0.2, label='Below ₦1K')
axes[0].set_title("Daily Closing Balance", fontweight='bold')
axes[0].set_ylabel("Balance (₦)")
axes[0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
axes[0].legend()
axes[0].tick_params(axis='x', rotation=45)

# Plot 2: Monthly average balance bar
colors = ['#2ecc71' if b > daily_balance['Balance'].mean() else '#e74c3c'
          for b in monthly_balance['Balance']]
axes[1].bar(monthly_balance['Month_str'], monthly_balance['Balance'],
            color=colors, edgecolor='white')
axes[1].axhline(daily_balance['Balance'].mean(), color='black',
                linestyle='--', label=f"Overall Avg ₦{daily_balance['Balance'].mean():,.0f}")
axes[1].set_title("Monthly Average Balance (Green = Above Avg, Red = Below)", fontweight='bold')
axes[1].set_ylabel("Balance (₦)")
axes[1].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
axes[1].tick_params(axis='x', rotation=45)
axes[1].legend()

# Plot 3: Balance change month over month
monthly_balance['MoM_Change'] = monthly_balance['Balance'].diff()
colors3 = ['#2ecc71' if x >= 0 else '#e74c3c' for x in monthly_balance['MoM_Change'].fillna(0)]
axes[2].bar(monthly_balance['Month_str'], monthly_balance['MoM_Change'].fillna(0),
            color=colors3, edgecolor='white')
axes[2].axhline(0, color='black', linewidth=0.8)
axes[2].set_title("Month-over-Month Balance Change (Green = Growing, Red = Shrinking)", fontweight='bold')
axes[2].set_ylabel("Change (₦)")
axes[2].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
axes[2].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.savefig('divine_balance_trajectory.png', bbox_inches='tight', dpi=150)
plt.show()
print("✅ Saved → divine_balance_trajectory.png")

# ── DIVINE: RECURRING TRANSACTION DETECTION ───────────────────────────────

divine = df[df['User'] == 'Divine Ehinomeh Martins'].copy()
divine['Date']      = pd.to_datetime(divine['Date'])
divine['YearMonth'] = divine['Date'].dt.to_period('M')

total_months = divine['YearMonth'].nunique()

# Clean description — strip noise to find recurring patterns
divine['Desc_Clean'] = divine['Description'].str.strip().str.lower()
divine['Desc_Clean'] = divine['Desc_Clean'].str.replace(r'\s+', ' ', regex=True)

# Group by description — count how many distinct months it appears in
recurrence = divine[divine['Debit'] > 0].groupby('Desc_Clean').agg(
    Months_Seen   = ('YearMonth', 'nunique'),
    Total_Times   = ('Debit', 'count'),
    Avg_Amount    = ('Debit', 'mean'),
    Total_Spent   = ('Debit', 'sum'),
    Category      = ('Category', 'first')
).reset_index()

# A transaction is "recurring" if it appears in 3+ distinct months
recurring = recurrence[recurrence['Months_Seen'] >= 3].sort_values(
    'Months_Seen', ascending=False).reset_index(drop=True)

recurring['Consistency_%'] = (recurring['Months_Seen'] / total_months * 100).round(1)
recurring['Desc_Display']  = recurring['Desc_Clean'].str.title().str[:40]

print("=" * 70)
print("DIVINE — RECURRING TRANSACTION DETECTION")
print("=" * 70)
print(f"\n📅 Total months in data : {total_months}")
print(f"🔁 Recurring patterns   : {len(recurring)} detected\n")

for _, row in recurring.iterrows():
    bar = '█' * int(row['Consistency_%'] / 10)
    print(f"  {row['Desc_Display']:<42} | {row['Months_Seen']:>2}/{total_months} months "
          f"| ₦{row['Avg_Amount']:>10,.0f} avg | {row['Consistency_%']}% {bar}")

# Total committed monthly spend from recurring transactions
monthly_committed = recurring['Avg_Amount'].sum()
print(f"\n💸 Estimated Monthly Committed Spend : ₦{monthly_committed:,.2f}")
print(f"   (what Divine reliably spends every month on recurring items)")

# ── VISUALISATION ──────────────────────────────────────────────────────────
top_recurring = recurring.head(15)

fig, axes = plt.subplots(1, 2, figsize=(18, 7))
fig.suptitle("Divine — Recurring Transaction Detection", fontsize=15, fontweight='bold')

colors = sns.color_palette('Blues_r', len(top_recurring))

# Left: how many months each recurring item appeared
axes[0].barh(top_recurring['Desc_Display'][::-1],
             top_recurring['Months_Seen'][::-1], color=colors, edgecolor='white')
axes[0].axvline(total_months, color='red', linestyle='--', label=f'All {total_months} months')
axes[0].set_title("Months Active (out of total)", fontweight='bold')
axes[0].set_xlabel("Number of Months")
axes[0].legend()
for i, (val, cons) in enumerate(zip(top_recurring['Months_Seen'][::-1],
                                     top_recurring['Consistency_%'][::-1])):
    axes[0].text(val + 0.1, i, f'{cons}%', va='center', fontsize=8)

# Right: average amount per occurrence
colors2 = sns.color_palette('Reds_r', len(top_recurring))
axes[1].barh(top_recurring['Desc_Display'][::-1],
             top_recurring['Avg_Amount'][::-1], color=colors2, edgecolor='white')
axes[1].set_title("Average Amount per Occurrence", fontweight='bold')
axes[1].set_xlabel("Amount (₦)")
axes[1].xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
for i, val in enumerate(top_recurring['Avg_Amount'][::-1]):
    axes[1].text(val + 100, i, f'₦{val:,.0f}', va='center', fontsize=8)

plt.tight_layout()
plt.savefig('divine_recurring.png', bbox_inches='tight', dpi=150)
plt.show()
print("✅ Saved → divine_recurring.png")

# ── DIVINE: SPENDING VELOCITY — How Fast Money Leaves After Credit ─────────

divine = df[df['User'] == 'Divine Ehinomeh Martins'].copy()
divine['Date'] = pd.to_datetime(divine['Date'])
divine = divine.sort_values('Date').reset_index(drop=True)

# Find every credit event then track spending in the days after
credits = divine[divine['Credit'] > 0].copy()
results = []

for _, credit_row in credits.iterrows():
    credit_date   = credit_row['Date']
    credit_amount = credit_row['Credit']

    # Get all debits in the 7 days after this credit
    window = divine[
        (divine['Date'] > credit_date) &
        (divine['Date'] <= credit_date + pd.Timedelta(days=7)) &
        (divine['Debit'] > 0)
    ]

    spent_1d = divine[
        (divine['Date'] > credit_date) &
        (divine['Date'] <= credit_date + pd.Timedelta(days=1)) &
        (divine['Debit'] > 0)
    ]['Debit'].sum()

    spent_3d = divine[
        (divine['Date'] > credit_date) &
        (divine['Date'] <= credit_date + pd.Timedelta(days=3)) &
        (divine['Debit'] > 0)
    ]['Debit'].sum()

    spent_7d = window['Debit'].sum()

    results.append({
        'Credit_Date'    : credit_date,
        'Credit_Amount'  : credit_amount,
        'Spent_1Day'     : spent_1d,
        'Spent_3Days'    : spent_3d,
        'Spent_7Days'    : spent_7d,
        'Pct_Gone_1Day'  : (spent_1d  / credit_amount * 100) if credit_amount > 0 else 0,
        'Pct_Gone_3Days' : (spent_3d  / credit_amount * 100) if credit_amount > 0 else 0,
        'Pct_Gone_7Days' : (spent_7d  / credit_amount * 100) if credit_amount > 0 else 0,
    })

velocity = pd.DataFrame(results)

print("=" * 65)
print("DIVINE — SPENDING VELOCITY AFTER CREDIT")
print("=" * 65)
print(f"\n📥 Total credit events analysed : {len(velocity)}")
print(f"\n⚡ On average, after money comes in:")
print(f"   Within 1 day  : ₦{velocity['Spent_1Day'].mean():>10,.2f} spent  "
      f"({velocity['Pct_Gone_1Day'].mean():.1f}% of credit gone)")
print(f"   Within 3 days : ₦{velocity['Spent_3Days'].mean():>10,.2f} spent  "
      f"({velocity['Pct_Gone_3Days'].mean():.1f}% of credit gone)")
print(f"   Within 7 days : ₦{velocity['Spent_7Days'].mean():>10,.2f} spent  "
      f"({velocity['Pct_Gone_7Days'].mean():.1f}% of credit gone)")

# Fastest burn events — top 5 times money disappeared quickest
print(f"\n🔥 Top 5 Fastest Burn Events (most % gone within 1 day):")
top_burns = velocity.nlargest(5, 'Pct_Gone_1Day')[
    ['Credit_Date','Credit_Amount','Spent_1Day','Pct_Gone_1Day']]
for _, row in top_burns.iterrows():
    print(f"   {row['Credit_Date'].date()} — received ₦{row['Credit_Amount']:,.0f} → "
          f"spent ₦{row['Spent_1Day']:,.0f} in 1 day ({row['Pct_Gone_1Day']:.0f}%)")

# ── VISUALISATION ──────────────────────────────────────────────────────────
fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle("Divine — Spending Velocity After Credit", fontsize=15, fontweight='bold')

# Plot 1: % of credit gone within 1 / 3 / 7 days (avg bar)
avg_pcts = [velocity['Pct_Gone_1Day'].mean(),
            velocity['Pct_Gone_3Days'].mean(),
            velocity['Pct_Gone_7Days'].mean()]
bar_colors = ['#e74c3c', '#e67e22', '#f1c40f']
bars = axes[0,0].bar(['1 Day', '3 Days', '7 Days'], avg_pcts,
                      color=bar_colors, edgecolor='white', width=0.5)
axes[0,0].set_title("Avg % of Credit Spent Within Window", fontweight='bold')
axes[0,0].set_ylabel("% of Credit Amount")
axes[0,0].set_ylim(0, max(avg_pcts) * 1.3)
for bar, val in zip(bars, avg_pcts):
    axes[0,0].text(bar.get_x() + bar.get_width()/2,
                   bar.get_height() + 0.5, f'{val:.1f}%',
                   ha='center', fontweight='bold', fontsize=11)

# Plot 2: Scatter — credit amount vs amount spent in 7 days
axes[0,1].scatter(velocity['Credit_Amount'], velocity['Spent_7Days'],
                  alpha=0.6, color='#8e44ad', edgecolors='white', s=60)
max_val = max(velocity['Credit_Amount'].max(), velocity['Spent_7Days'].max())
axes[0,1].plot([0, max_val], [0, max_val], 'r--', linewidth=1, label='Spent = Received')
axes[0,1].set_title("Credit Amount vs Spent in 7 Days", fontweight='bold')
axes[0,1].set_xlabel("Credit Amount (₦)")
axes[0,1].set_ylabel("Spent in 7 Days (₦)")
axes[0,1].xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
axes[0,1].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
axes[0,1].legend()

# Plot 3: % gone in 1 day over time
axes[1,0].plot(velocity['Credit_Date'], velocity['Pct_Gone_1Day'],
               marker='o', color='#e74c3c', linewidth=1.5, markersize=4, alpha=0.7)
axes[1,0].axhline(velocity['Pct_Gone_1Day'].mean(), color='black',
                  linestyle='--', label=f"Avg {velocity['Pct_Gone_1Day'].mean():.1f}%")
axes[1,0].axhline(100, color='red', linestyle=':', linewidth=1, label='100% gone')
axes[1,0].set_title("% of Credit Spent Within 1 Day (Over Time)", fontweight='bold')
axes[1,0].set_ylabel("% Spent")
axes[1,0].tick_params(axis='x', rotation=45)
axes[1,0].legend()

# Plot 4: Distribution of burn rate (1 day %)
axes[1,1].hist(velocity['Pct_Gone_1Day'].clip(upper=200), bins=20,
               color='#e67e22', edgecolor='white', alpha=0.85)
axes[1,1].axvline(velocity['Pct_Gone_1Day'].mean(), color='red',
                  linestyle='--', label=f"Avg {velocity['Pct_Gone_1Day'].mean():.1f}%")
axes[1,1].set_title("Distribution of 1-Day Burn Rate", fontweight='bold')
axes[1,1].set_xlabel("% of Credit Spent in 1 Day")
axes[1,1].set_ylabel("Frequency")
axes[1,1].legend()

plt.tight_layout()
plt.savefig('divine_spending_velocity.png', bbox_inches='tight', dpi=150)
plt.show()
print("✅ Saved → divine_spending_velocity.png")

# ── CHRISTOPHER OPARA (OPAY) — Full Spending Analysis ─────────────────────

christopher = df[
    (df['User'] == 'Christopher Opara') &
    (df['Bank'] == 'OPay')
].copy()
christopher['Date']      = pd.to_datetime(christopher['Date'])
christopher['IsWeekend'] = christopher['Date'].dt.dayofweek.isin([5,6]).astype(int)
christopher['DayOfWeek'] = christopher['Date'].dt.day_name()
christopher['YearMonth'] = christopher['Date'].dt.to_period('M')

print(f"Christopher's transactions : {len(christopher)}")
print(f"Date range                 : {christopher['Date'].min().date()} → {christopher['Date'].max().date()}")
print(f"Total Spent                : ₦{christopher['Debit'].sum():,.2f}")
print(f"Total Received             : ₦{christopher['Credit'].sum():,.2f}")
print(f"Net Position               : ₦{(christopher['Credit'].sum() - christopher['Debit'].sum()):,.2f}")

fig, axes = plt.subplots(3, 2, figsize=(16, 18))
fig.suptitle("Christopher Opara (OPay) — Spending Analysis",
             fontsize=16, fontweight='bold', y=1.01)

# Plot 1: Spending by Category
cat_spend = christopher.groupby('Category')['Debit'].sum().sort_values(ascending=True)
cat_spend = cat_spend[cat_spend > 0]
colors = sns.color_palette("RdYlGn_r", len(cat_spend))
cat_spend.plot(kind='barh', ax=axes[0,0], color=colors, edgecolor='white')
axes[0,0].set_title("Total Spend by Category", fontweight='bold')
axes[0,0].set_xlabel("Amount (₦)")
axes[0,0].xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
for i, v in enumerate(cat_spend):
    axes[0,0].text(v + 100, i, f'₦{v:,.0f}', va='center', fontsize=7)

# Plot 2: Monthly Debit vs Credit
monthly = christopher.groupby(christopher['Date'].dt.to_period('M')).agg(
    Debit=('Debit','sum'), Credit=('Credit','sum')).reset_index()
monthly['Date'] = monthly['Date'].astype(str)
x = range(len(monthly))
width = 0.35
axes[0,1].bar([i - width/2 for i in x], monthly['Debit'],  width, label='Debit (Spent)',     color='#e74c3c', alpha=0.85)
axes[0,1].bar([i + width/2 for i in x], monthly['Credit'], width, label='Credit (Received)', color='#2ecc71', alpha=0.85)
axes[0,1].set_xticks(list(x))
axes[0,1].set_xticklabels(monthly['Date'], rotation=45, ha='right', fontsize=8)
axes[0,1].set_title("Monthly Income vs Expenses", fontweight='bold')
axes[0,1].set_ylabel("Amount (₦)")
axes[0,1].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
axes[0,1].legend()

# Plot 3: Category Transaction Count (pie)
cat_count = christopher['Category'].value_counts()
top_cats  = cat_count[:7]
other_sum = cat_count[7:].sum()
if other_sum > 0:
    top_cats['Other Categories'] = other_sum
axes[1,0].pie(top_cats, labels=top_cats.index, autopct='%1.1f%%',
              startangle=140, colors=sns.color_palette('Set2', len(top_cats)))
axes[1,0].set_title("Transaction Count by Category", fontweight='bold')

# Plot 4: Daily Spending Trend
daily = christopher.groupby('Date')['Debit'].sum().reset_index()
daily['Rolling7'] = daily['Debit'].rolling(7).mean()
axes[1,1].fill_between(daily['Date'], daily['Debit'], alpha=0.3, color='#e74c3c', label='Daily Spend')
axes[1,1].plot(daily['Date'], daily['Rolling7'], color='#c0392b', linewidth=2, label='7-Day Rolling Avg')
axes[1,1].set_title("Daily Spending Trend", fontweight='bold')
axes[1,1].set_ylabel("Amount (₦)")
axes[1,1].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
axes[1,1].legend()
axes[1,1].tick_params(axis='x', rotation=45)

# Plot 5: Spending by Day of Week
dow_order  = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
dow_spend  = christopher.groupby('DayOfWeek')['Debit'].sum().reindex(dow_order)
bar_colors = ['#e74c3c' if d in ['Saturday','Sunday'] else '#3498db' for d in dow_order]
dow_spend.plot(kind='bar', ax=axes[2,0], color=bar_colors, edgecolor='white')
axes[2,0].set_title("Spending by Day of Week\n(Red = Weekend)", fontweight='bold')
axes[2,0].set_ylabel("Amount (₦)")
axes[2,0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
axes[2,0].tick_params(axis='x', rotation=45)

# Plot 6: Top 10 Largest Transactions
top10 = christopher.nlargest(10, 'Debit')[['Date','Category','Description','Debit']].copy()
axes[2,1].barh(range(len(top10)), top10['Debit'], color='#e67e22', edgecolor='white')
axes[2,1].set_yticks(range(len(top10)))
axes[2,1].set_yticklabels([f"{r['Description'][:25]}..." for _, r in top10.iterrows()], fontsize=8)
axes[2,1].set_title("Top 10 Largest Transactions", fontweight='bold')
axes[2,1].set_xlabel("Amount (₦)")
axes[2,1].xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))

plt.tight_layout()
plt.savefig('christopher_opay_eda.png', bbox_inches='tight', dpi=150)
plt.show()
print("✅ Christopher OPay EDA complete")

# ── CHRISTOPHER OPARA (OPAY) — Detailed Category Breakdown ────────────────

christopher = df[
    (df['User'] == 'Christopher Opara') &
    (df['Bank'] == 'OPay')
].copy()
christopher['Date']      = pd.to_datetime(christopher['Date'])
christopher['YearMonth'] = christopher['Date'].dt.to_period('M')

print("=" * 60)
print("CHRISTOPHER OPARA (OPAY) — DETAILED SPENDING BREAKDOWN")
print("=" * 60)

summary = christopher.groupby('Category').agg(
    Transactions = ('Debit', 'count'),
    Total_Spent  = ('Debit', 'sum'),
    Avg_Per_Txn  = ('Debit', 'mean'),
    Max_Txn      = ('Debit', 'max')
).sort_values('Total_Spent', ascending=False).round(2)

summary['% of Total Spend'] = (summary['Total_Spent'] / summary['Total_Spent'].sum() * 100).round(1)
summary['Total_Spent']      = summary['Total_Spent'].apply(lambda x: f'₦{x:,.2f}')
summary['Avg_Per_Txn']      = summary['Avg_Per_Txn'].apply(lambda x: f'₦{x:,.2f}')
summary['Max_Txn']          = summary['Max_Txn'].apply(lambda x: f'₦{x:,.2f}')

print(summary.to_string())

print("\n")
print(f"💰 Total Spent         : ₦{christopher['Debit'].sum():,.2f}")
print(f"💵 Total Received      : ₦{christopher['Credit'].sum():,.2f}")
print(f"📊 Net Position        : ₦{(christopher['Credit'].sum() - christopher['Debit'].sum()):,.2f}")
print(f"📅 Avg Daily Spend     : ₦{christopher.groupby('Date')['Debit'].sum().mean():,.2f}")
print(f"📅 Avg Monthly Spend   : ₦{christopher.groupby(christopher['Date'].dt.to_period('M'))['Debit'].sum().mean():,.2f}")
print(f"🔢 Most Active Category: {christopher['Category'].value_counts().index[0]} ({christopher['Category'].value_counts().iloc[0]} transactions)")

# ── CHRISTOPHER OPARA (OPAY) — Financial Health Summary ───────────────────

christopher = df[
    (df['User'] == 'Christopher Opara') &
    (df['Bank'] == 'OPay')
].copy()
christopher['Date'] = pd.to_datetime(christopher['Date'])

total_in     = christopher['Credit'].sum()
total_out    = christopher['Debit'].sum()
net          = total_in - total_out
savings_rate = ((total_in - total_out) / total_in * 100) if total_in > 0 else 0

print("=" * 60)
print("CHRISTOPHER OPARA (OPAY) — FINANCIAL HEALTH SUMMARY")
print("=" * 60)

print(f"\n💵 Total Income (Credits)  : ₦{total_in:,.2f}")
print(f"💸 Total Expenses (Debits) : ₦{total_out:,.2f}")
print(f"💰 Net Savings             : ₦{net:,.2f}")
print(f"📊 Savings Rate            : {savings_rate:.1f}%")

if savings_rate >= 20:
    health = "🟢 HEALTHY — Saving more than 20% of income"
elif savings_rate >= 10:
    health = "🟡 MODERATE — Saving between 10–20% of income"
elif savings_rate >= 0:
    health = "🟠 AT RISK — Saving less than 10% of income"
else:
    health = "🔴 CRITICAL — Spending more than earning"
print(f"🏥 Financial Health        : {health}")

# ── CHRISTOPHER OPARA (OPAY) — Monthly Financial Flow & Savings Rate ───────

christopher = df[
    (df['User'] == 'Christopher Opara') &
    (df['Bank'] == 'OPay')
].copy()
christopher['Date'] = pd.to_datetime(christopher['Date'])

monthly = christopher.groupby(christopher['Date'].dt.to_period('M')).agg(
    Income  = ('Credit', 'sum'),
    Expense = ('Debit',  'sum')
).reset_index()
monthly['Savings']      = monthly['Income'] - monthly['Expense']
monthly['Savings_Rate'] = (monthly['Savings'] / monthly['Income'] * 100).round(1)
monthly['Date']         = monthly['Date'].astype(str)

fig, axes = plt.subplots(2, 1, figsize=(14, 10))
fig.suptitle("Christopher (OPay) — Monthly Financial Flow & Savings Rate",
             fontsize=14, fontweight='bold')

# Plot 1: Monthly net savings bar
colors = ['#2ecc71' if x >= 0 else '#e74c3c' for x in monthly['Savings']]
axes[0].bar(monthly['Date'], monthly['Savings'], color=colors, edgecolor='white')
axes[0].axhline(0, color='black', linewidth=0.8, linestyle='--')
axes[0].set_title("Monthly Net Savings (Green = Saved, Red = Overspent)", fontweight='bold')
axes[0].set_ylabel("Amount (₦)")
axes[0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
axes[0].tick_params(axis='x', rotation=45)
for i, (val, date) in enumerate(zip(monthly['Savings'], monthly['Date'])):
    axes[0].text(i, val + (500 if val >= 0 else -2000), f'₦{val:,.0f}',
                ha='center', fontsize=7, fontweight='bold')

# Plot 2: Savings rate line
axes[1].plot(monthly['Date'], monthly['Savings_Rate'],
             marker='o', color='#8e44ad', linewidth=2.5, markersize=8)
axes[1].axhline(20, color='green', linewidth=1, linestyle='--', label='Healthy (20%)')
axes[1].axhline(0,  color='red',   linewidth=1, linestyle='--', label='Break Even (0%)')
axes[1].fill_between(range(len(monthly)), monthly['Savings_Rate'], 0,
                     where=[x >= 0 for x in monthly['Savings_Rate']],
                     alpha=0.15, color='green')
axes[1].fill_between(range(len(monthly)), monthly['Savings_Rate'], 0,
                     where=[x < 0 for x in monthly['Savings_Rate']],
                     alpha=0.15, color='red')
axes[1].set_title("Monthly Savings Rate (%)", fontweight='bold')
axes[1].set_ylabel("Savings Rate (%)")
axes[1].set_xticks(range(len(monthly)))
axes[1].set_xticklabels(monthly['Date'], rotation=45, ha='right', fontsize=8)
axes[1].legend()

plt.tight_layout()
plt.savefig('christopher_opay_savings_trend.png', bbox_inches='tight', dpi=150)
plt.show()
print(monthly[['Date','Income','Expense','Savings','Savings_Rate']].to_string(index=False))
print("✅ Saved → christopher_opay_savings_trend.png")

# ── CHRISTOPHER OPARA (OPAY) — Spending Behaviour Patterns ────────────────

christopher = df[
    (df['User'] == 'Christopher Opara') &
    (df['Bank'] == 'OPay')
].copy()
christopher['Date']      = pd.to_datetime(christopher['Date'])
christopher['IsWeekend'] = christopher['Date'].dt.dayofweek.isin([5,6]).astype(int)
christopher['DayOfWeek'] = christopher['Date'].dt.day_name()
christopher['YearMonth'] = christopher['Date'].dt.to_period('M')

print("=" * 60)
print("CHRISTOPHER OPARA (OPAY) — SPENDING BEHAVIOUR PATTERNS")
print("=" * 60)

# Weekend vs Weekday
weekend_spend = christopher[christopher['IsWeekend'] == 1]['Debit'].sum()
weekday_spend = christopher[christopher['IsWeekend'] == 0]['Debit'].sum()
weekend_txns  = len(christopher[christopher['IsWeekend'] == 1])
weekday_txns  = len(christopher[christopher['IsWeekend'] == 0])

print(f"\n📅 WEEKEND vs WEEKDAY SPENDING")
print(f"   Weekend Total : ₦{weekend_spend:,.2f} across {weekend_txns} transactions")
print(f"   Weekday Total : ₦{weekday_spend:,.2f} across {weekday_txns} transactions")
print(f"   Weekend Avg   : ₦{weekend_spend/weekend_txns if weekend_txns > 0 else 0:,.2f} per transaction")
print(f"   Weekday Avg   : ₦{weekday_spend/weekday_txns if weekday_txns > 0 else 0:,.2f} per transaction")

# Monthly spending stats
monthly_exp = christopher.groupby(christopher['Date'].dt.to_period('M'))['Debit'].sum()
print(f"\n📆 MONTHLY SPENDING PATTERNS")
print(f"   Most Expensive Month : {monthly_exp.idxmax()} — ₦{monthly_exp.max():,.2f}")
print(f"   Cheapest Month       : {monthly_exp.idxmin()} — ₦{monthly_exp.min():,.2f}")
print(f"   Average Monthly Spend: ₦{monthly_exp.mean():,.2f}")
print(f"   Monthly Std Dev      : ₦{monthly_exp.std():,.2f}")

# Transaction size distribution
print(f"\n💳 TRANSACTION SIZE DISTRIBUTION")
bins   = [0, 500, 2000, 10000, 50000, float('inf')]
labels = ['Micro (₦0–500)', 'Small (₦501–2K)', 'Medium (₦2K–10K)', 'Large (₦10K–50K)', 'Very Large (₦50K+)']
debit_only = christopher[christopher['Debit'] > 0].copy()
debit_only['TxnSize'] = pd.cut(debit_only['Debit'], bins=bins, labels=labels)
txn_dist = debit_only['TxnSize'].value_counts().sort_index()
for label, count in txn_dist.items():
    pct = count / txn_dist.sum() * 100
    print(f"   {label:<25}: {count:>4} transactions ({pct:.1f}%)")

# Category consistency across months
total_months = christopher['YearMonth'].nunique()
print(f"\n🔄 CATEGORY CONSISTENCY (out of {total_months} months)")
cat_months = christopher.groupby('Category')['YearMonth'].nunique().sort_values(ascending=False)
for cat, months in cat_months.items():
    pct = months / total_months * 100
    bar = '█' * int(pct / 10)
    print(f"   {cat:<22}: {months}/{total_months} months ({pct:.0f}%) {bar}")

# ── CHRISTOPHER OPARA (OPAY) — Filtered Pie Chart by Month / Week ──────────

christopher = df[
    (df['User'] == 'Christopher Opara') &
    (df['Bank'] == 'OPay')
].copy()
christopher['Date']      = pd.to_datetime(christopher['Date'])
christopher['YearMonth'] = christopher['Date'].dt.to_period('M')
christopher['YearWeek']  = christopher['Date'].dt.to_period('W')

# ── CONFIG ────────────────────────────────────────────────────────────────
FILTER_BY = 'month'    # 'month'  or  'week'
PERIOD    = '2025-10'  # month: '2025-10' | week: run once to see available weeks

# ── Show available periods ─────────────────────────────────────────────────
if FILTER_BY == 'month':
    available = sorted([str(p) for p in christopher['YearMonth'].unique()])
    print("📅 Available months:", available)
    subset = christopher[christopher['YearMonth'].astype(str) == PERIOD]
    period_label = PERIOD
elif FILTER_BY == 'week':
    available = sorted([str(p) for p in christopher['YearWeek'].unique()])
    print("📅 Available weeks:", available)
    subset = christopher[christopher['YearWeek'].astype(str) == PERIOD]
    period_label = f"Week {PERIOD}"

# ── Count & print ──────────────────────────────────────────────────────────
cat_count = subset['Category'].value_counts()
print(f"\n📊 Transaction Count by Category — {period_label}")
print(cat_count.to_string())

# ── Pie + Bar side by side ─────────────────────────────────────────────────
if cat_count.empty:
    print("⚠️  No data for this period — check your PERIOD value above")
else:
    fig, axes = plt.subplots(1, 2, figsize=(16, 7))
    fig.suptitle(f"Christopher (OPay) — Transaction Count by Category ({period_label})",
                 fontsize=14, fontweight='bold')

    colors = sns.color_palette('Set2', len(cat_count))

    # Pie
    wedges, texts, autotexts = axes[0].pie(
        cat_count, labels=cat_count.index, autopct='%1.1f%%',
        startangle=140, colors=colors, pctdistance=0.82
    )
    for at in autotexts: at.set_fontsize(9)
    axes[0].set_title("Share (%)", fontweight='bold')

    # Bar
    bars = axes[1].bar(cat_count.index, cat_count.values, color=colors, edgecolor='white')
    axes[1].set_title("Absolute Count", fontweight='bold')
    axes[1].set_ylabel("Number of Transactions")
    axes[1].tick_params(axis='x', rotation=45)
    for bar, val in zip(bars, cat_count.values):
        axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,
                     str(val), ha='center', va='bottom', fontweight='bold')

    plt.tight_layout()
    plt.savefig(f'christopher_opay_pie_{FILTER_BY}_{PERIOD}.png', bbox_inches='tight', dpi=150)
    plt.show()
    print(f"✅ Saved → christopher_opay_pie_{FILTER_BY}_{PERIOD}.png")

# ── ALL MONTHS: one pie per month in a grid ───────────────────────────────
months = sorted(christopher['YearMonth'].unique())
cols = 4
rows = (len(months) + cols - 1) // cols

fig, axes = plt.subplots(rows, cols, figsize=(cols*5, rows*4.5))
fig.suptitle("Christopher (OPay) — Transaction Count by Category (All Months)",
             fontsize=15, fontweight='bold', y=1.01)
axes = axes.flatten()
palette = sns.color_palette('Set2', 10)

for i, month in enumerate(months):
    sub = christopher[christopher['YearMonth'] == month]
    cc  = sub['Category'].value_counts()
    ax  = axes[i]
    if cc.empty:
        ax.set_visible(False)
        continue
    ax.pie(cc, labels=cc.index, autopct='%1.0f%%',
           startangle=140, colors=palette[:len(cc)], pctdistance=0.80)
    for t in ax.texts: t.set_fontsize(7)
    ax.set_title(str(month), fontweight='bold', fontsize=10)

for j in range(i+1, len(axes)):
    axes[j].set_visible(False)

plt.tight_layout()
plt.savefig('christopher_opay_all_monthly_pies.png', bbox_inches='tight', dpi=150)
plt.show()
print("✅ All monthly pies → christopher_opay_all_monthly_pies.png")

# ── CHRISTOPHER OPARA (OPAY) — Who He Sends Money To ─────────────────────

christopher = df[
    (df['User'] == 'Christopher Opara') &
    (df['Bank'] == 'OPay')
].copy()
christopher['Date']      = pd.to_datetime(christopher['Date'])
christopher['YearMonth'] = christopher['Date'].dt.to_period('M')
christopher['YearWeek']  = christopher['Date'].dt.to_period('W')
christopher['Year']      = christopher['Date'].dt.year

# Keep only outgoing P2P transfers
sent = christopher[
    (christopher['Category'] == 'P2P Transfer') &
    (christopher['Description'].str.lower().str.startswith('transfer to', na=False))
].copy()

# Extract recipient name
sent['Recipient'] = sent['Description'].str.replace(
    r'^Transfer to\s+', '', case=False, regex=True).str.strip()

# ── CONFIG ────────────────────────────────────────────────────────────────
FILTER_BY = 'month'    # 'month'  |  'week'  |  'year'
PERIOD    = '2025-10'  # month: '2025-10' | week: '2025-W41' | year: 2025
TOP_N     = 10

# ── Filter ────────────────────────────────────────────────────────────────
if FILTER_BY == 'month':
    available = sorted([str(p) for p in sent['YearMonth'].unique()])
    print("📅 Available months:", available)
    subset = sent[sent['YearMonth'].astype(str) == PERIOD]
    period_label = PERIOD
elif FILTER_BY == 'week':
    available = sorted([str(p) for p in sent['YearWeek'].unique()])
    print("📅 Available weeks:", available)
    subset = sent[sent['YearWeek'].astype(str) == str(PERIOD)]
    period_label = f"Week {PERIOD}"
elif FILTER_BY == 'year':
    available = sorted(sent['Year'].unique().tolist())
    print("📅 Available years:", available)
    subset = sent[sent['Year'] == int(PERIOD)]
    period_label = str(PERIOD)

# ── Aggregate ─────────────────────────────────────────────────────────────
recipient_count  = subset.groupby('Recipient')['Debit'].count().sort_values(ascending=False).head(TOP_N)
recipient_amount = subset.groupby('Recipient')['Debit'].sum().reindex(recipient_count.index)

print(f"\n📊 Top {TOP_N} Recipients — {period_label}")
for r, count, amt in zip(recipient_count.index, recipient_count.values, recipient_amount.values):
    print(f"   {r:<45}: {count:>3}x  ₦{amt:,.2f}")

# ── Chart ─────────────────────────────────────────────────────────────────
if recipient_count.empty:
    print("⚠️  No outgoing transfers for this period — check your PERIOD value")
else:
    fig, axes = plt.subplots(1, 2, figsize=(18, 6))
    fig.suptitle(f"Christopher (OPay) — Who He Sends Money To ({period_label})",
                 fontsize=14, fontweight='bold')

    colors  = sns.color_palette('Blues_r', len(recipient_count))
    colors2 = sns.color_palette('Reds_r',  len(recipient_amount))

    # Left: frequency
    bars = axes[0].barh(recipient_count.index[::-1], recipient_count.values[::-1],
                        color=colors, edgecolor='white')
    axes[0].set_title(f"Number of Transfers (Top {TOP_N})", fontweight='bold')
    axes[0].set_xlabel("Transfer Count")
    for bar, val in zip(bars, recipient_count.values[::-1]):
        axes[0].text(bar.get_width() + 0.1, bar.get_y() + bar.get_height()/2,
                     f'{val}x', va='center', fontweight='bold', fontsize=9)

    # Right: total amount
    bars2 = axes[1].barh(recipient_amount.index[::-1], recipient_amount.values[::-1],
                         color=colors2, edgecolor='white')
    axes[1].set_title(f"Total Amount Sent (Top {TOP_N})", fontweight='bold')
    axes[1].set_xlabel("Amount (₦)")
    axes[1].xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
    for bar, val in zip(bars2, recipient_amount.values[::-1]):
        axes[1].text(bar.get_width() + 500, bar.get_y() + bar.get_height()/2,
                     f'₦{val:,.0f}', va='center', fontsize=8)

    plt.tight_layout()
    plt.savefig(f'christopher_opay_recipients_{FILTER_BY}_{PERIOD}.png', bbox_inches='tight', dpi=150)
    plt.show()
    print(f"\n✅ Saved → christopher_opay_recipients_{FILTER_BY}_{PERIOD}.png")

# ── ANYANWU TOBECHUKWU FREDRICK (GTBANK) — Full Spending Analysis ──────────

fredrick = df[df['User'] == 'Anyanwu Tobechukwu Fredrick'].copy()
fredrick['Date']      = pd.to_datetime(fredrick['Date'])
fredrick['IsWeekend'] = fredrick['Date'].dt.dayofweek.isin([5,6]).astype(int)
fredrick['DayOfWeek'] = fredrick['Date'].dt.day_name()
fredrick['YearMonth'] = fredrick['Date'].dt.to_period('M')

print(f"Fredrick's transactions : {len(fredrick)}")
print(f"Date range              : {fredrick['Date'].min().date()} → {fredrick['Date'].max().date()}")
print(f"Total Spent             : ₦{fredrick['Debit'].sum():,.2f}")
print(f"Total Received          : ₦{fredrick['Credit'].sum():,.2f}")
print(f"Net Position            : ₦{(fredrick['Credit'].sum() - fredrick['Debit'].sum()):,.2f}")

fig, axes = plt.subplots(3, 2, figsize=(16, 18))
fig.suptitle("Anyanwu Tobechukwu Fredrick (GTBank) — Spending Analysis",
             fontsize=16, fontweight='bold', y=1.01)

# Plot 1: Spending by Category
cat_spend = fredrick.groupby('Category')['Debit'].sum().sort_values(ascending=True)
cat_spend = cat_spend[cat_spend > 0]
colors = sns.color_palette("RdYlGn_r", len(cat_spend))
cat_spend.plot(kind='barh', ax=axes[0,0], color=colors, edgecolor='white')
axes[0,0].set_title("Total Spend by Category", fontweight='bold')
axes[0,0].set_xlabel("Amount (₦)")
axes[0,0].xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
for i, v in enumerate(cat_spend):
    axes[0,0].text(v + 100, i, f'₦{v:,.0f}', va='center', fontsize=7)

# Plot 2: Monthly Debit vs Credit
monthly = fredrick.groupby(fredrick['Date'].dt.to_period('M')).agg(
    Debit=('Debit','sum'), Credit=('Credit','sum')).reset_index()
monthly['Date'] = monthly['Date'].astype(str)
x = range(len(monthly))
width = 0.35
axes[0,1].bar([i - width/2 for i in x], monthly['Debit'],  width, label='Debit (Spent)',     color='#e74c3c', alpha=0.85)
axes[0,1].bar([i + width/2 for i in x], monthly['Credit'], width, label='Credit (Received)', color='#2ecc71', alpha=0.85)
axes[0,1].set_xticks(list(x))
axes[0,1].set_xticklabels(monthly['Date'], rotation=45, ha='right', fontsize=8)
axes[0,1].set_title("Monthly Income vs Expenses", fontweight='bold')
axes[0,1].set_ylabel("Amount (₦)")
axes[0,1].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
axes[0,1].legend()

# Plot 3: Category Transaction Count (pie)
cat_count = fredrick['Category'].value_counts()
top_cats  = cat_count[:7]
other_sum = cat_count[7:].sum()
if other_sum > 0:
    top_cats['Other Categories'] = other_sum
axes[1,0].pie(top_cats, labels=top_cats.index, autopct='%1.1f%%',
              startangle=140, colors=sns.color_palette('Set2', len(top_cats)))
axes[1,0].set_title("Transaction Count by Category", fontweight='bold')

# Plot 4: Daily Spending Trend
daily = fredrick.groupby('Date')['Debit'].sum().reset_index()
daily['Rolling7'] = daily['Debit'].rolling(7).mean()
axes[1,1].fill_between(daily['Date'], daily['Debit'], alpha=0.3, color='#e74c3c', label='Daily Spend')
axes[1,1].plot(daily['Date'], daily['Rolling7'], color='#c0392b', linewidth=2, label='7-Day Rolling Avg')
axes[1,1].set_title("Daily Spending Trend", fontweight='bold')
axes[1,1].set_ylabel("Amount (₦)")
axes[1,1].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
axes[1,1].legend()
axes[1,1].tick_params(axis='x', rotation=45)

# Plot 5: Spending by Day of Week
dow_order  = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
dow_spend  = fredrick.groupby('DayOfWeek')['Debit'].sum().reindex(dow_order)
bar_colors = ['#e74c3c' if d in ['Saturday','Sunday'] else '#3498db' for d in dow_order]
dow_spend.plot(kind='bar', ax=axes[2,0], color=bar_colors, edgecolor='white')
axes[2,0].set_title("Spending by Day of Week\n(Red = Weekend)", fontweight='bold')
axes[2,0].set_ylabel("Amount (₦)")
axes[2,0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))
axes[2,0].tick_params(axis='x', rotation=45)

# Plot 6: Top 10 Largest Transactions
top10 = fredrick.nlargest(10, 'Debit')[['Date','Category','Description','Debit']].copy()
axes[2,1].barh(range(len(top10)), top10['Debit'], color='#e67e22', edgecolor='white')
axes[2,1].set_yticks(range(len(top10)))
axes[2,1].set_yticklabels([f"{r['Description'][:25]}..." for _, r in top10.iterrows()], fontsize=8)
axes[2,1].set_title("Top 10 Largest Transactions", fontweight='bold')
axes[2,1].set_xlabel("Amount (₦)")
axes[2,1].xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'₦{x:,.0f}'))

plt.tight_layout()
plt.savefig('fredrick_gtbank_eda.png', bbox_inches='tight', dpi=150)
plt.show()
print("✅ Fredrick GTBank EDA complete")









#prediction models

# ── DIVINE FULL LOG — MONTHLY SPENDING PREDICTION ─────────────────────────────
print("🔮 Divine Ehinomeh Martins — Monthly Spending Prediction (Full Log)")
print("Using only 6 columns: Date, Category, Description, Debit, Credit, Balance\n")

# Filter only Divine's full data
divine = df[df['User'] == 'Divine Ehinomeh Martins'].copy()

print(f"Total transactions in Divine's full log: {len(divine):,}")
print(f"Date range: {divine['Date'].min().date()} → {divine['Date'].max().date()}")
print(f"Number of months: {divine['Date'].dt.to_period('M').nunique()}\n")

# Use only the 6 columns
divine_pred = divine[['Date', 'Category', 'Description', 'Debit', 'Credit', 'Balance']].copy()

# Aggregate to monthly level
divine_pred['YearMonth'] = divine_pred['Date'].dt.to_period('M')

monthly_divine = divine_pred.groupby('YearMonth').agg(
    Total_Spent=('Debit', 'sum'),           # This is what we predict next month
    Total_Received=('Credit', 'sum'),
    Avg_Balance=('Balance', 'mean'),
    Transaction_Count=('Date', 'count'),
    Unique_Categories=('Category', 'nunique')
).reset_index()

monthly_divine['YearMonth'] = monthly_divine['YearMonth'].astype(str)
monthly_divine['Year'] = pd.to_datetime(monthly_divine['YearMonth']).dt.year
monthly_divine['Month'] = pd.to_datetime(monthly_divine['YearMonth']).dt.month

# Time-based features from full history
monthly_divine['Spent_Lag1'] = monthly_divine['Total_Spent'].shift(1)
monthly_divine['Spent_Lag2'] = monthly_divine['Total_Spent'].shift(2)
monthly_divine['Received_Lag1'] = monthly_divine['Total_Received'].shift(1)
monthly_divine['Balance_Lag1'] = monthly_divine['Avg_Balance'].shift(1)
monthly_divine['Spent_Rolling3'] = monthly_divine['Total_Spent'].rolling(window=3, min_periods=1).mean()

# Target = NEXT month's Total_Spent
monthly_divine['Target_Next_Spent'] = monthly_divine['Total_Spent'].shift(-1)

# Drop only rows where we cannot create the target (last month)
monthly_divine = monthly_divine.dropna(subset=['Target_Next_Spent']).reset_index(drop=True)

print(f"✅ Final dataset for modeling: {len(monthly_divine)} months")
print("\nPreview of the data we will use for training:")
print(monthly_divine[['YearMonth', 'Total_Spent', 'Target_Next_Spent', 'Spent_Lag1',
                      'Spent_Rolling3', 'Avg_Balance']].head(8))

print("\nLast 3 months (will be used for testing):")
print(monthly_divine[['YearMonth', 'Total_Spent', 'Target_Next_Spent']].tail(3))

